### ISSUE TITLE
'PointerEvent' can't be assigned to the parameter type 'PointerDownEvent'

### ISSUE THREAD

**Issue by andylai** [fireslime/photo_view#426] opened 2021-05-28 07:57 UTC
Just launch this component got this issue.

latest flutter version
Flutter (Channel master, 2.3.0-17.0.pre.47, on macOS 11.2.3 20D91 darwin-x64, locale en-MY)
Android toolchain - develop for Android devices (Android SDK version 30.0.2)
 Android Studio (version 4.1)
 
../../../../.pub-cache/hosted/pub.dartlang.org/photo_view-0.11.1/lib/src/core/photo_view_gesture_detector.dart:106:29: Error: The argument type 'PointerEvent' can't be assigned to the parameter type 'PointerDownEvent'.
 - 'PointerEvent' is from 'package:flutter/src/gestures/events.dart' ('../../../../flutter/packages/flutter/lib/src/gestures/events.dart').
 - 'PointerDownEvent' is from 'package:flutter/src/gestures/events.dart' ('../../../../flutter/packages/flutter/lib/src/gestures/events.dart').
    super.addAllowedPointer(event);

**Comment by jkyeo** [comment] 2021-05-28 07:58
same here

**Comment by tuemaytinh1981** [comment] 2021-05-30 03:44
I also had this problem when updating to ios 14. Maybe the function was changed for the latest iOs version.

Xcode's output:
↳
    ../../../.pub-cache/hosted/pub.dartlang.org/photo_view-0.11.1/lib/src/core/photo_view_gesture_detector.dart:106:29: Error: The argument type 'PointerEvent' can't be assigned to the parameter type 'PointerDownEvent'.
     - 'PointerEvent' is from 'package:flutter/src/gestures/events.dart' ('../../../Development/flutter/packages/flutter/lib/src/gestures/events.dart').
     - 'PointerDownEvent' is from 'package:flutter/src/gestures/events.dart' ('../../../Development/flutter/packages/flutter/lib/src/gestures/events.dart').
        super.addAllowedPointer(event);
                                ^

**Comment by getpu** [comment] 2021-05-30 15:10
I have a same issue...

**Comment by renancaraujo** [comment] 2021-05-30 20:44
Dupe of https://github.com/fireslime/photo_view/issues/423


Full disclosure of temporary usage here: https://github.com/fireslime/photo_view/issues/423#issuecomment-847681903

**Closed by renancaraujo** 2021-05-30 20:44 UTC
