### ISSUE TITLE
How to drag and drop the picture

### ISSUE THREAD

**Issue by bombert** [fireslime/photo_view#315] opened 2020-08-16 06:22 UTC
Hey guys, I want to zoom and move the picture. While so far it seems that there is only zooming method, do you have solutions to drag the picture? Thanks.

**Comment by gamestap99** [comment] 2020-08-18 14:12
same the proplem. drag page not working

**Comment by renancaraujo** [comment] 2020-08-18 20:18
What do you mean drag image?

> Hey guys, I want to zoom and move the picture
Are you talking about the pan gesture?


> drag page not working
Or you mean change page on the gallery?

**Comment by gamestap99** [comment] 2020-08-19 06:54
@renancaraujo  yes!

**Comment by gamestap99** [comment] 2020-08-19 07:00
@renancaraujo change page on the gallery some time be error. i try drag to next page but it not working

**Comment by renancaraujo** [comment] 2020-08-20 10:41
Oh, @gamestap99 for that follow #304

@bombert you issue looks like dupe of #216, please either confirm that or give more information about your problem.

**Comment by renancaraujo** [comment] 2020-08-28 10:26
Yeas, when adding physics.

**Closed** 2020-09-10 14:05 UTC
Labels: question
