### ISSUE TITLE
How do I show an image that is smaller than the phone screen?

### ISSUE THREAD

**Issue by mongugay** [fireslime/photo_view#306] opened 2020-08-10 09:39 UTC
**Describe the request**
How do I show an image that is smaller than the phone screen? Now, with these parameters, it expands to the size of the phone screen. An image of 200x200 pixels on a large screen looks very stretched.

**To Reproduce**
There is my code:

```  
Widget _buildImages(BuildContext context) {
    return PhotoViewGallery.builder(
      itemCount: _images.length,
      pageController: _controller,
      backgroundDecoration: BoxDecoration(
        color: Colors.white,
      ),
      builder: (BuildContext context, int index) {
        return PhotoViewGalleryPageOptions(
          imageProvider: _images[index].image,
          initialScale: PhotoViewComputedScale.contained,
          minScale: PhotoViewComputedScale.contained * 1.0,
          maxScale: PhotoViewComputedScale.covered * 2.0,
          basePosition: Alignment.center,
        );
      },
    );
  }
```
Screenshots
![image](https://user-images.githubusercontent.com/1773504/89769161-5b38f400-db05-11ea-8fd7-613059cdc63d.png)

**Comment by renancaraujo** [comment] 2020-08-11 09:22
```dart
          initialScale: 1.0,
          minScale: <something smaller than 1.0>
          maxScale:  <something bigger than 1.0>
```

**Comment by renancaraujo** [comment] 2020-08-11 09:23
Just use:

```dart
    initialScale: 1.0,
    minScale: <less than 1.0>
    maxScale:  <more than 1.0>
```

**Comment by renancaraujo** [comment] 2020-08-28 10:25
For organizational sake, I shall close this. If there is anything else to discuss, feel free to retake the discussion.

**Closed by renancaraujo** 2020-08-28 10:25 UTC
Labels: question

**Comment by tomekit** [comment] 2023-10-22 09:23
`initialScale: 1.0` works fine, but if you have a big image then once it's opened only portion of that image will be visible.
Is there any way to mimic the: `Boxfit.contain` behavior? https://flutter.github.io/assets-for-api-docs/assets/painting/box_fit_contain.png
It seems that `PhotoView`'s: `initialScale: PhotoViewComputedScale.contained` isn't doing it.

**Comment by tomekit** [comment] 2023-10-22 11:07
I think the issue is more complex with: `photo_view` zoom feature.
The: `defaultScaleStateCycle` method defines the state transitions
These are the states:
```
initial -> covering -> originalSize -> initial ...
```
It works fine for most of the images, but if image is much smaller than the screen, then it gets stretched. The small image looks good in the: `originalSize`, so in theory I could change the workflow in: `defaultScaleStateCycle` to start with the `originalSize`... but then it would broke workflow for most of the images (which are bigger than the screen), as they would start with zoomed mode.

## PhotoViewScaleState.initial - undesired for small image
![Screenshot from 2023-10-22 13-04-12](https://github.com/bluefireteam/photo_view/assets/7759113/95efca37-1f99-46ca-b77c-cb353a2ca594)

## PhotoViewScaleState.originalSize - good for small image, undesired for big images
![Screenshot from 2023-10-22 13-04-35](https://github.com/bluefireteam/photo_view/assets/7759113/19ada8ff-48e8-47c8-ab6d-e8ce8a293921)

Ideally if there is an option to set the `original` size if image is smaller than the screen.

**Comment by tomekit** [comment] 2023-10-22 12:48
If there was a way to get the image size from the image provider and based on that conditionally provide custom `initialSize and `scaleStateCycle`. I am feeding `PhotoView` with: `imageProvider: CachedNetworkImageProvider` I am not really sure if I can easily load an image and get the size before `PhotoView` gets called.
