### ISSUE TITLE
[BUG] ERROR: The argument type 'PointerEvent' can't be assigned to the parameter type 'PointerDownEvent'.

### ISSUE THREAD

**Issue by dpedrinha** [fireslime/photo_view#429] opened 2021-06-08 22:29 UTC
**Describe the bug**

After updating Android Studio (4.2.1), Gradle (4.1.0), Flutter (Channel master, 2.3.0-17.0.pre.266) and Dart (2.14.0) to the latest versions, I'm getting the following error when building:

/../AppData/Local/Pub/Cache/hosted/pub.dartlang.org/photo_view-0.11.1/lib/src/core/photo_vie
w_gesture_detector.dart:106:29: Error: The argument type 'PointerEvent' can't be assigned to the paramete
r type 'PointerDownEvent'.
 - 'PointerEvent' is from 'package:flutter/src/gestures/events.dart' ('/../flutter/packages/flutter/l
ib/src/gestures/events.dart').
 - 'PointerDownEvent' is from 'package:flutter/src/gestures/events.dart' ('/../flutter/packages/flutt
er/lib/src/gestures/events.dart').
    super.addAllowedPointer(event);

**To Reproduce**

**What is the current behavior?**

**Expected behavior**

**Screenshots**

**Which versions of Flutter/Photo View, and which browser / OS are affected by this issue? Did this work in previous versions of Photo View?**
photo_view: 0.11.1

**Comment by dpedrinha** [comment] 2021-06-08 22:50
Changing `core/photo_view_gesture_detector.dart` line 101 to `void addAllowedPointer(PointerDownEvent event) {` makes the error disappear, but I don't know the implications of it.

**Comment by renancaraujo** [comment] 2021-06-09 09:10
Dupe of #423

**Closed by renancaraujo** 2021-06-09 09:10 UTC
Labels: bug

**Comment by Jackjun724** [comment] 2021-06-20 08:03
> Changing `core/photo_view_gesture_detector.dart` line 101 to `void addAllowedPointer(PointerDownEvent event) {` makes the error disappear, but I don't know the implications of it.
> 
> I need to test it further. But anyway, I'll test it for my application only so the dev should review this change.
Maybe you can refer to this link [doc](https://flutter.dev/docs/release/breaking-changes/gesture-recognizer-add-allowed-pointer)
